### ISSUE TITLE
Deprecation Warnings in Django 1.9

### ISSUE THREAD

**Issue by nachopro** [django-macaddress/django-macaddress#22]
https://docs.djangoproject.com/en/1.8/releases/1.8/#subfieldbase

fields.py:12: Removed In Django1.10
Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.

**Comment by kra3** [comment]
@merinos do you mind sending a pull request or taking your change set?

**Comment by merinos** [comment]
@kra3 my commit don't pass tests. It seems that from_db_value doens't work like SubfieldBase (it's not call at the same time). Functionally my patch seems to work but when I try to save an object with a wrong mac address, it doesn't throw the correct exception (AddrFormatError instead of ValidationError).

**Comment by cyberjacob** [comment]
Looks like `from_db_value()` needs to be implemented to fix the tests
